### ISSUE TITLE
Null Reference Exception thrown on startup

### ISSUE THREAD

**Issue by securigy** [MarkLTX/TracerX#6] opened 2022-10-20 01:19 UTC
I worked with TracerX for years and it is great, but today I accounted Null Reference Exception right on startup. I thought it is a problem with VS2022 and switched back to VS2019 but the problem started to appear there too. So instead of NuGet I download the source code and added it as a project. Never the less the problem does not go away. This line throws the exception.
`public partial class AddinModule : AddinExpress.MSO.ADXAddinModule
    {
        // Declare a Logger instance for use by this class.
        private static readonly Logger Log = Logger.GetLogger("AddinModule");
    }`
When I dig deeper I see that exception is thrown at this line 1363 in Logger.cs
`result = Assembly.GetEntryAssembly().GetName().Name;`

System.NullReferenceException: 'Object reference not set to an instance of an object.'

Please advise.

**Comment by MarkLTX** [comment] 2022-10-20 20:01
Does this only happen in the debugger?   An exception there is actually pretty common, but that line of code is in a try/catch and the exception shouldn't be able to propagate.  So I'm wondering if you're running in the debugger with it configured to break when that exception is thrown.

**Comment by securigy** [comment] 2022-10-20 21:17
Yes, it happens in the Debugger (VS2022) and I think the setting was to break when exception happens on that line. I completely recreated the project (since I could not continue) and the exception disappeared... strange... But thank you for you response, anyway. Good to know there is a "father" for this product - it is amazingly great! I use it since 2011, I think.
Leon
    On Thursday, October 20, 2022 at 01:02:07 PM PDT, MarkLTX ***@***.***> wrote:  
 
 

Does this only happen in the debugger?   An exception there is actually pretty common, but that line of code is in a try/catch and the exception shouldn't be able to propagate.  So I'm wondering if you're running in the debugger with it configured to break when that exception is thrown. Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Leon ***@***.***> Date: 10/19/22 8:20 PM (GMT-06:00) To: MarkLTX/TracerX ***@***.***> Cc: Subscribed ***@***.***> Subject: [MarkLTX/TracerX] Null Reference Exception thrown on startup (Issue #6) 
I worked with TracerX for years and it is great, but today I accounted Null Reference Exception right on startup. I thought it is a problem with VS2022 and switched back to VS2019 but the problem started to appear there too. So instead of NuGet I download the source code and added it as a project. Never the less the problem does not go away. This line throws the exception.
public partial class AddinModule : AddinExpress.MSO.ADXAddinModule { // Declare a Logger instance for use by this class. private static readonly Logger Log = Logger.GetLogger("AddinModule"); }
When I dig deeper I see that exception is thrown at this line 1363 in Logger.cs
result = Assembly.GetEntryAssembly().GetName().Name;
System.NullReferenceException: 'Object reference not set to an instance of an object.'
Please advise.

**Comment by securigy** [comment] 2022-12-27 21:24
Sorry to write about it again, but this time I created another project (VSTO Word Add-In) and am receiving the same exception...(in Debug mode). Not sure what to do - recreating the project this time seems too lame...

**Comment by securigy** [comment] 2022-12-27 21:39
What kind of setting I need to enable/disable under Tools > Options > Debug ?

**Comment by securigy** [comment] 2022-12-27 21:55
Apparently it is not Debug options setting - I have the same setting in the projects that works with TracerX.

**Comment by MarkLTX** [comment] 2022-12-31 15:52
Is it still happening on this specific line of code (line 1363 in Logger.cs)?

      result = Assembly.GetEntryAssembly().GetName().Name;

This part of the code is trying to determine the name of your program/application to use as the default name of the log file.  The problem is that Assembly.GetEntryAssembly() will return null if your application is hosted by unmanaged code.  This is often the case for web apps hosted by IIS and, presumably, other web servers.  However it works fine for non-web apps like console apps, Windows services, Winforms (desktop) apps, etc.  Perhaps that's the reason the exception is thrown in some of your projects and not others.  I don't know anything about VSTO Word Add-Ins so I don't know which category that falls in but I wouldn't be surprised to learn that Word isn't a .NET program.

The "bug" here is that the code relies on the exception being thrown and caught rather than avoiding the exception by checking for null.  As far as I know this code works fine in a production environment so it's more of an inconvenience than an error.

I will fix this by checking if Assembly.GetEntryAssembly() returns null instead of allowing the exception to occur.

Have you found the setting in Visual Studio where you can enable/disable the setting to "always break when System.NullReferenceException is thrown"?  Until I can publish a fix for this issue, you can either disable that setting or live with hitting the exception every time you run your app in the debugger.

**Comment by securigy** [comment] 2022-12-31 18:02
VSTO type of products are MS Office Add-Ins. They are all based on COM interfaces but their interfaces in C#/.NET.
You were right the first time - I simply disable exception throwing for this - not a great solution, but a quick one. 

I probably should post another issue separately, but I frequently unable to use TracerX logging in methods that are using async/await pattern. It usually happens on leaving the function. I think in those case I simple comment out using(Log.VerboseCall()) to avoid the exception from TracerX.

**Comment by MarkLTX** [comment] 2022-12-31 19:49
Are you using TracerX via NuGet or by downloading the assembly published here on GitHub?  I just want to know the best way to deliver a new version for you to try.

I will also try to fix the async/await issue.  It can occur when your code enters a "using (Log.VerboseCall())" block in one thread and then exits the block in a different thread.  There may not be a good fix because changing threads in the middle of a method call violates a basic assumption (i.e. that that can't happen).

**Comment by securigy** [comment] 2022-12-31 21:46
I did not look at the source but what about switching back to main thread just before exiting the TracerX "using" scope?

    On Saturday, December 31, 2022 at 11:49:41 AM PST, MarkLTX ***@***.***> wrote:  
 
 


Are you using TracerX via NuGet or by downloading the assembly published here on GitHub? I just want to know the best way to deliver a new version for you to try.

I will also try to fix the async/await issue. It can occur when your code enters a "using (Log.VerboseCall())" block in one thread and then exits the block in a different thread. There may not be a good fix because changing threads in the middle of a method call violates a basic assumption (i.e. that that can't happen).

**Comment by securigy** [comment] 2022-12-31 22:45
And yes, I am using TracerX via NuGet - this is most convenient - although years back I was using it as a source - some clients mandate to have all source in their possession, no matter what... 
    On Saturday, December 31, 2022 at 11:49:41 AM PST, MarkLTX ***@***.***> wrote:  
 
 


Are you using TracerX via NuGet or by downloading the assembly published here on GitHub? I just want to know the best way to deliver a new version for you to try.

I will also try to fix the async/await issue. It can occur when your code enters a "using (Log.VerboseCall())" block in one thread and then exits the block in a different thread. There may not be a good fix because changing threads in the middle of a method call violates a basic assumption (i.e. that that can't happen).

**Comment by MarkLTX** [comment] 2023-01-01 00:28
Please try the latest release (7.3.0) and let me know if the null reference issue is resolved or not.

**Comment by MarkLTX** [comment] 2023-01-12 20:50
I have fixed the problem that occurs with async/await. Please try the latest NuGet release (TracerX-Logger 8.0).

**Closed as completed** 2023-01-12 20:51 UTC

**Comment by securigy** [comment] 2023-01-12 21:06
That's awesome. Now I will be able to add the 'using' statements in all async/await functions! Thank you, I will try it at the first chance I have in my current project.
    On Thursday, January 12, 2023 at 12:51:05 PM PST, MarkLTX ***@***.***> wrote:  
 
 


I have fixed the problem that occurs with async/await. Please try the latest NuGet release (TracerX-Logger 8.0).
